libmusic: fix build error
Forgot to include <cassert>:

	[..]/libmusic/src/chord_detector.cpp: In function ‘td_t anatomist::Decimate(const td_t&, size_t)’:
	[..]/libmusic/src/chord_detector.cpp:89:5: error: ‘assert’ was not declared in this scope
	   89 |     assert(factor > 0);
	      |     ^~~~~~